import turtle
myturtle = turtle.Turtle()
myturtle.penup()
myturtle.goto(50,75)
myturtle.pendown()
myturtle.forward(200)
myturtle.left(90)
myturtle.forward(200)
myturtle.left(90)
myturtle.forward(200)
myturtle.left(90)
myturtle.forward(200)
turtle.done()